//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantSystem.Models.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Merchant
    {
        public long Id { get; set; }
        public string MerchantNo { get; set; }
        public string MerchantName { get; set; }
        public int MerchantType { get; set; }
        public int MerchantStatus { get; set; }
        public decimal BalanceAmount { get; set; }
        public decimal FrozenAmount { get; set; }
        public decimal DeductionUnitPrice { get; set; }
        public string WithdrawType { get; set; }
        public string LegalPersonRealName { get; set; }
        public string LegalPersonIdCardNo { get; set; }
        public string LegalPersonMobile { get; set; }
        public string MerchantPublicBankCode { get; set; }
        public string MerchantPublicBankName { get; set; }
        public string MerchantPublicBankAddress { get; set; }
        public string MerchantPublicBankMobile { get; set; }
        public string USCC { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
