//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantSystem.Models.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysLog
    {
        public string Id { get; set; }
        public string LoginUser { get; set; }
        public string IPAddr { get; set; }
        public string OpContent { get; set; }
        public System.DateTime OpTime { get; set; }
    }
}
